apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-broker-1
  name: kafka-broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-broker-1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka-broker-1
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              # value: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
              # value: PLAINTEXT://localhost:9092
              # value: PLAINTEXT://kafka-broker-1:9092
              value: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker-1:29092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:latest
          name: kafka-broker-1
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
