apiVersion: v1
kind: Service
metadata:
  name: consumer-kafka-service
  labels:
    app: consumer-kafka
spec:
  selector:
    app: consumer-kafka
  ports:
    - protocol: TCP
      port: 8080  # Puerto que expone el servicio dentro del clúster
      targetPort: 8080  # Puerto al que se conecta dentro del contenedor
  type: ClusterIP  # Tipo predeterminado para comunicación interna en el clúster
